config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :api do
    namespace :services do
      resources :supplies, only: %i[index]
      resources :sat_catalogs, only: %i[index]
    end
  end

  namespace :admin do
    root to: 'main#index'
    resources :users
  end

  namespace :reports do
    resources :lumps, only: [:index]
    resources :products, only: [:index]
  end

  scope module: 'config/production', path: 'categories/:id' do
    get '/get_supplies_codes', to: 'categories#get_supplies_codes'
  end

  scope module: 'config/production', path: 'crops' do
    get '/get_crops', to: 'crops#get_crops'
    get '/:id/get_pests', to: 'crops#get_pests'
    get '/:id/get_deseases', to: 'crops#get_deseases'
  end

  scope module: 'config/production', path: 'treatments' do
    get '/treatment_exist', to: 'treatments#treatment_exist'
  end

  namespace :config do
    resources :taxes
    resources :drivers
    resources :units
    resources :boxes
    resources :delivery_addresses
    resources :client_brands
    resources :currencies
    namespace :production do
      root to: 'main#index'
      resources :categories
      resources :treatments
      resources :active_ingredients
      resources :presentations
      resources :supplies do
        member do
          delete '/delete_image', to: 'supplies#delete_image_attachment'
        end
        resources :treatments
        resources :presentations, only: %i[update edit show]
        resources :active_ingredients, only: %i[update edit show]
      end
      resources :ranches do
        resources :areas
        resources :perforations
      end
      resources :production_units, except: %i[show]
      resources :weight_units, only: %i[index create destroy]
      resources :irrigation_types, only: %i[index create destroy]
      resources :areas
      resources :activities
      resources :perforations
      resources :stages
      resources :sub_stages
      resources :crops do
        resources :deseases
        resources :pests
        member do
          get '/get_colors', to: 'crops#get_colors'
          get '/get_qualities', to: 'crops#get_qualities'
          get '/get_sizes', to: 'crops#get_sizes'
          get '/get_packages', to: 'crops#get_packages'
        end
      end
      resources :products
      resources :sizes
      resources :qualities
      resources :colors
      resources :packages
      resources :hosts
      resources :damages
      resources :pests do
        resources :treatments
        resources :hosts
        resources :damages
        member do
          patch '/update_pictures', to: 'pests#update_pictures'
        end
      end
      resources :deseases do
        resources :treatments
        resources :hosts
        resources :damages
        member do
          patch '/update_pictures', to: 'deseases#update_pictures'
        end
      end
    end
    namespace :admin do
      resources :expense_concepts
    end
    resources :clients, except: [:edit]
  end

  namespace :logistic do
    root to: 'main#index'
    resources :freights
    resources :carriers do
      resources :drivers
      resources :units
      resources :freights
      resources :boxes
      resources :contacts, except: [:index]
      resources :bank_accounts, except: [:index]
    end
    resources :bank_accounts, except: [:index]
    resources :contacts, except: [:index]
    resources :units
    resources :drivers
    resources :boxes
    namespace :config do
      root to: 'main#index'
      resources :box_types
      resources :unit_brands
    end
  end

  namespace :commercial do
    root to: 'main#index' # Comercial dashboard
    resources :requisitions do
      get '/print', to: 'requisitions#print'
      patch '/update_status', to: 'requisitions#update_status'
    end
    resources :providers do
      patch :update_status
      resources :addresses
      get :supplies
      patch :add_supplies
      patch :delete_supply
    end
    namespace :config do
      root to: 'main#index'
      resources :delivery_types, except: [:show, :new]
      resources :provider_categories do
        get '/get_subcategories', to: 'provider_categories#get_subcategories'
      end
    end
  end

  namespace :credit do
    resources :payment_advances
  end

  namespace :billing do
    resources :pre_bills do
      patch :update_discounts
      patch :manual_stamp
      patch :cancel
    end
  end

  namespace :crm do
    root to: 'main#index' # CRM dashboard
    resources :report_prices, except: %i[index show]
    resources :products, only: %i[edit update]
    resources :expenses, except: %i[index show] do
      collection do
        get 'build_detail'
      end
    end
    resources :clients do
      collection do
        get 'delivery_addresses'
      end
      resources :contacts, except: [:index]
      resources :delivery_addresses, except: [:index]
      resources :contracts, only: %i[new edit show]
      resources :bank_accounts, except: [:index]
      resources :fiscals, except: [:index]

      get '/get_delivery_address', to: 'clients#get_delivery_address'
      get '/get_contacts', to: 'clients#get_contacts'
    end
    resources :sales do
      patch '/expenses', to: 'sales#update_expenses'
      patch '/products', to: 'sales#update_products'
      patch '/reports', to: 'sales#update_reports'
      patch '/cancel', to: 'sales#cancel'
      patch '/set_contract', to: 'sales#set_contract'
      patch '/update_currency', to: 'sales#update_currency'
      patch '/documents', to: 'sales#update_documents'
      get '/to_collect', to: 'sales#to_collect'
      get '/manage', to: 'sales#manage'
      get '/get_report_products', to: 'sales#get_report_products'
    end
    resources :contracts, only: %i[create update]
    resources :bank_accounts, except: [:index]

    resources :delivery_addresses, except: [:index] do
      collection do
        patch :update_prices
      end
    end
    resources :contacts, except: [:index]
    resources :fiscals, except: [:index]
    resources :quotes do
      get '/print', to: 'quotes#print'
      patch '/update_status', to: 'quotes#update_status'
      patch '/cancel', to: 'quotes#cancel'
      collection do
        get :consolidate
      end
    end
    resources :sales_orders do
      get '/print', to: 'sales_orders#print'
      patch '/cancel', to: 'sales_orders#cancel'
      get '/print_aditional_data', to: 'sales_orders#print_aditional_data'
    end

    namespace :config do
      root to: 'main#index'
      resources :expenses
    end
  end

  namespace :directories do
    resources :carriers do
      resources :drivers
    end
    resources :clients
  end

  namespace :addresses do
    resources :countries
    resources :states
    resources :municipalities
    # #End points to addres
    get '/addresses/states', to: 'addresses#states'
    get '/addresses/municipalities', to: 'addresses#municipalities'
    get '/addresses/locations', to: 'addresses#locations'
  end

  namespace :traceability do
    resources :cicles do
      patch '/update_status', to: 'cicles#update_status'
    end
    resources :areas, only: [:index, :show]
    resources :harvests do
      collection do
        get '/get_crop', to: 'harvests#get_crop'
      end
    end
  end

  resources :carriers do
    get '/get_drivers', to: 'carriers#get_drivers'
    get '/get_units', to: 'carriers#get_units'
    get '/get_boxes', to: 'carriers#get_boxes'
  end

  resources :shipments do
    get '/consolidate', to: 'shipments#consolidate'
    get '/print', to: 'shipments#print'
    get '/print_responsive', to: 'shipments#print_responsive'
  end

  resources :companies
  resources :profile, except: [:new] do
    get '/avatar', to: 'profile#avatar'
    get '/change_password', to: 'profile#change_password'
  end

  devise_for :users
  root to: 'dashboard#index'
end

app/models/stage.rb
# frozen_string_literal: true

class Stage < ApplicationRecord
  validates :name, presence: true
end

app/controllers/config/production/active_ingredients_controller.rb
# frozen_string_literal: true

module Config
  module Production
    class ActiveIngredientsController < ApplicationController
      before_action :find_active_ingredient, only: %i[destroy edit update show]

      add_breadcrumb 'Produccion', :config_production_root_path
      add_breadcrumb 'Ingredientes Activos', :config_production_active_ingredients_path

      def index
        @index_facade = ActiveIngredients::IndexFacade.new(params)
        @active_ingredient = ActiveIngredient.new
      end

      def create
        @active_ingredient = ActiveIngredient.new(active_ingredients_params)
        if @active_ingredient.save
          flash[:notice] = "<i class='fa fa-check-circle mr-1 s-18'></i>  Ingrediente activo creado correctamente"
          redirect_to config_production_active_ingredients_path
        else
          @index_facade = ActiveIngredients::IndexFacade.new(params)
          render :index
        end
      end

      def edit
        add_breadcrumb 'Editar'
      end

      def show
        add_breadcrumb 'Detalle'
      end

      def update
        if params[:supply_id].present?
          @active_ingredient.update!(active_ingredients_params)
          @active_ingredient_supply.update!(active_ingredient_supply_params)
          flash[:notice] = 'El Ingrediente activo fue actualizado correctamente.'
          return redirect_to config_production_supply_url(@supply.id, tab: :active_ingredients)
        end
        @active_ingredient.update!(active_ingredients_params)
        flash[:notice] = "<i class='fa fa-check-circle mr-1 s-18'></i>  Ingrediente activo actualizado correctamente"
        redirect_to config_production_active_ingredients_path
      rescue ActiveRecord::RecordInvalid
        render :edit
      end

      def destroy
        @active_ingredient.destroy
      end

      private

      def active_ingredients_params
        params.require(:active_ingredient).permit(:name,
                                                  active_ingredient_supplies_attributes: %i[id supply_id active_ingredient_id _destroy])
      end

      def active_ingredient_supply_params
        params.require(:active_ingredient).require(:active_ingredient_supply).permit(:percentage)
      end

      def find_active_ingredient
        if params[:supply_id].present?
          @supply = Supply.find(params[:supply_id])
          @active_ingredient_supply = ActiveIngredientSupply.where(supply_id: params[:supply_id], active_ingredient_id: params[:id]).first
        end
        @active_ingredient = ActiveIngredient.find(params[:id])
      end
    end
  end
end

app/controllers/config/production/activities_controller.rb
# frozen_string_literal: true

module Config
  module Production
    class ActivitiesController < ApplicationController
      before_action :find_activity, only: %i[show edit update destroy]

      add_breadcrumb 'Produccion', :config_production_root_path
      add_breadcrumb 'Actividades', :config_production_activities_path

      def index
        @index_facade = Activities::IndexFacade.new(params)
        @activity = Activity.new
      end

      def new
        add_breadcrumb 'Nuevo'
        @activity = Activity.new
      end

      def create
        @activity = Activity.new(activity_params)
        if @activity.save
          flash[:notice] = "<i class='fa fa-check-circle mr-1 s-18'></i>  Actividad creada correctamente"
          redirect_to config_production_activities_path
        else
          @index_facade = Activities::IndexFacade.new(params)
          render :index
        end
      end

      def edit
        add_breadcrumb 'Editar'
      end

      def show
        add_breadcrumb 'Detalle de Aactividad'
      end

      def update
        if @activity.update(activity_params)
          flash[:notice] = 'La Aactividad fue actualizada correctamente.'
          redirect_to config_production_activities_path
        else
          render :edit
        end
      end

      def destroy
        @activity.destroy
      end

      private

      def activity_params
        params.require(:activity).permit(:action, :production_unit_id, :jornals)
      end

      def find_activity
        @activity = Activity.find(params[:id])
      end
    end
  end
end

app/controllers/config/production/areas_controller.rb
# frozen_string_literal: true

module Config
  module Production
    class AreasController < ApplicationController
      before_action :find_area, only: %i[show edit update destroy]
      before_action :set_ranch, only: %i[new update]

      add_breadcrumb 'Produccion', :config_production_root_path
      add_breadcrumb 'Areas', :config_production_areas_path

      def index
        @index_facade = Areas::IndexFacade.new(params)
      end

      def new
        add_breadcrumb 'Nuevo'
        @area = Area.new
      end

      def create
        @area = Area.new(area_params)
        @area.ranch_id = params[:ranch_id] if params[:ranch_id].present?
        if @area.save
          flash[:notice] = "<i class='fa fa-check-circle mr-1 s-18'></i>  Area creada correctamente"
          redirect_to new_config_production_area_path
        else
          render :new
        end
      end

      def edit
        add_breadcrumb 'Editar'
      end

      def show
        add_breadcrumb 'Detalle de Area'
      end

      def update
        if @area.update(area_params)
          flash[:notice] = 'La Area fue actualizada correctamente.'
          redirect_to config_production_area_url(@area)
        else
          render :edit
        end
      end

      def destroy
        @area.destroy
      end

      private

      def area_params
        params.require(:area).permit(:name, :territory, :irrigation_type_id, :ranch_id)
      end

      def find_area
        @area = Area.find(params[:id])
        @obj = @area
      end

      def set_ranch
        @ranch = Ranch.find(params[:ranch_id]) if params[:ranch_id]
      end
    end
  end
end

app/controllers/config/production/categories_controller.rb
# frozen_string_literal: true

module Config
  module Production
    class CategoriesController < ApplicationController
      before_action :find_category, only: %i[destroy edit update]

      add_breadcrumb 'Produccion', :config_production_root_path
      add_breadcrumb 'Categorias', :config_production_categories_path

      def index
        @index_facade = Categories::IndexFacade.new(params)
        @category = Category.new
      end

      def create
        @category = Category.new(categories_params)
        if @category.save
          flash[:notice] = "<i class='fa fa-check-circle mr-1 s-18'></i>  Categoria creada correctamente"
          redirect_to config_production_categories_path
        else
          @index_facade = Categories::IndexFacade.new(params)
          render :index
        end
      end

      def edit
        add_breadcrumb 'Editar'
      end

      def update
        if @category.update(categories_params)
          flash[:notice] = "<i class='fa fa-check-circle mr-1 s-18'></i>  Categoria actualizada correctamente"
          redirect_to config_production_categories_path
        else
          render :edit
        end
      end

      def destroy
        @category.destroy
      end

      def get_supplies_codes
        category = Category.find(params[:id])
        render json: { codes: category.supplies.pluck(:code).uniq.compact, category: category.name }
      end

      private

      def categories_params
        params.require(:category).permit(:name)
      end

      def find_category
        @category = Category.find(params[:id])
      end
    end
  end
end

app/controllers/config/production/colors_controller.rb
# frozen_string_literal: true

class Config::Production::ColorsController < ApplicationController
  before_action :set_object, only: %i[show edit update destroy]

  add_breadcrumb 'Produccion', :config_production_root_path
  add_breadcrumb 'Colores', :config_production_colors_path

  def index
    @colors = Color.paginate(page: params[:page], per_page: 16)
    search if params[:q].present?
  end

  def new
    add_breadcrumb 'Nuevo'
    @color = Color.new
  end

  def edit
    add_breadcrumb 'Editar'
  end

  def show
    add_breadcrumb 'Detalle'
  end

  def create
    @color = Color.new(color_params)
    respond_to do |format|
      if @color.save
        format.html { redirect_to config_production_colors_url, notice: 'Color creado.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    if @color.update(color_params)
      flash[:notice] = "Tamaño #{@color.name} Actualizado"
      redirect_to config_production_colors_url
    else
      render :edit
    end
  end

  def destroy
    @color.destroy
  end

  private

  def search
    q = Regexp.escape(params[:q])

    @colors = @colors.where('name ~* ?', q)
  end

  def color_params
    params.require(:color).permit(:name)
  end

  def set_object
    @color = Color.find(params[:id])
  end
end

app/controllers/config/production/main_controller.rb
# frozen_string_literal: true

module Config::Production
  class MainController < ApplicationController
    add_breadcrumb 'Produccion', :config_production_root_path
    def index; end
  end
end

app/views/config/production/stages/_form.html.slim
= simple_form_for([:config_production, @stage], data: { controller: 'masks address slim-select' }, html: { autocomplete: 'off' }) do |f|
	.row
		.col-lg-12
			h6.s-16
				svg.svg-inline--fa.fa-info-circle.fa-w-16.h-16.mr-2.mb-1 aria-hidden="true" data-icon="info-circle" data-prefix="fas" focusable="false" role="img" viewbox=("0 0 512 512") xmlns="http://www.w3.org/2000/svg" 
					path d=("M256 8C119.043 8 8 119.083 8 256c0 136.997 111.043 248 248 248s248-111.003 248-248C504 119.083 392.957 8 256 8zm0 110c23.196 0 42 18.804 42 42s-18.804 42-42 42-42-18.804-42-42 18.804-42 42-42zm56 254c0 6.627-5.373 12-12 12h-88c-6.627 0-12-5.373-12-12v-24c0-6.627 5.373-12 12-12h12v-64h-12c-6.627 0-12-5.373-12-12v-24c0-6.627 5.373-12 12-12h64c6.627 0 12 5.373 12 12v100h12c6.627 0 12 5.373 12 12v24z") fill="currentColor" 
				span General
	.form-group.mb-1  
		.row

			.col-lg-10
				= f.input :name, required: true, autofocus: true, input_html: { class: 'form-control form-control-sm ' }
	hr
	.form-actions.text-right
		= link_to config_production_stages_path, notice: 'Are you sure?', class: 'btn btn-default btn-sm pl-1' do
			i.fas.fa-chevron-left.mx-2.s-10
			span Volver
		button.btn.btn-dark-blue.btn-sm.ml-2.pl-1 type="submit"
			svg.feather.feather-save fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox=("0 0 24 24") width="24" xmlns="http://www.w3.org/2000/svg" 
			  path d=("M19 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11l5 5v11a2 2 0 0 1-2 2z") 
			  polyline points=("17 21 17 13 7 13 7 21") 
			  polyline points=("7 3 7 8 15 8") 
			span Guardar

app/views/config/production/stages/edit.html.slim
section.content-header.pb-0
  .container
    .row
      .col-12.text-left.pr-2.s-12
        = render "shared/breadcrumbs_nav"
    .row.mb-2
      .col-12
        h5 = "Editar Etapa".upcase 
section.content
  .container
    = render "shared/form_info"
    .row
      .col-md-12
        .card
          .card-body.p-3
            .row
              .col-md-7
                = render 'form', states: @states, municipalities: @municipalities

app/views/config/production/stages/index.html.slim
section.content-header.pb-0
  .container-fluid
    .row
      .col-12.text-left.pr-2.s-12
        = render "shared/breadcrumbs_nav"
    .row.mb-2
      .col-12
        h5 = "gestión de etapas".upcase
section.content data-controller="users"
  .container-fluid
    .row
      .col-12
        .card
          .card-header
            h5.s-14.my-0 = "Agregar etapas".upcase
          .card-body
            = render "form"
    = render "shared/alerts"
    .row
      .col-md-12
        .card
          .card-header.p-2.pb-1.bg-light-gray
            .row
              .col-md-6.col-sm-12
                = render 'shared/search_form', search_path: config_production_stages_path do
                  = text_field_tag(:q, params[:q], class: 'form-control form-control-sm', placeholder: 'Buscar por nombre')
          .card-body.table-responsive.p-0
            table.table.table-sm.table-hover.text-nowrap.table-bordered.s-14
              thead
                tr.bg-light-gray
                  th style=("width: 5%")  #
                  th Nombre
                  th.text-center colspan="2" style=("width: 12%") Acciónes
              tbody#tbody
                - if @index_facade.stages.empty?
                  tr
                    td.text-center colspan="9"
                    	span.s-12 Sin registros
                - else
                  - @index_facade.stages.each do |stage|
                    tr
                      td = stage.id
                      td = stage.name.upcase
                      td.text-center
                        .btn-group
                          = link_to edit_config_production_stage_path(stage), title: "Editar", 'data-toggle' => 'tooltip', 'data-placement' => 'left', class: "btn btn-xs btn-default" do
                            svg.feather.feather-edit fill="none" height="13" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox=("0 0 24 24") width="16" xmlns="http://www.w3.org/2000/svg" 
                              path d=("M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7") 
                              path d=("M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z")
                          = link_to config_production_stage_path(stage), title: "Eliminar", class: "btn btn-xs btn-danger ml-1", data: { placement: 'left', toggle: 'tooltip', controller: 'users', behavior: 'delete' } do
                              i.fas.fa-trash
                             
          .card-footer.p-2.pb-1.bg-light-gray
            .row
              .col-lg-12.d-flex.justify-content-center
                .digg_pagination.mt-2.s-14
                  = will_paginate @index_facade.stages, :container => false, :page_links => true