config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :api do
    namespace :services do
      resources :supplies, only: %i[index]
      resources :sat_catalogs, only: %i[index]
    end
  end

  namespace :admin do
    root to: 'main#index'
    resources :users
  end

  namespace :reports do
    resources :lumps, only: [:index]
    resources :products, only: [:index]
  end

  scope module: 'config/production', path: 'categories/:id' do
    get '/get_supplies_codes', to: 'categories#get_supplies_codes'
  end

  scope module: 'config/production', path: 'crops' do
    get '/get_crops', to: 'crops#get_crops'
    get '/:id/get_pests', to: 'crops#get_pests'
    get '/:id/get_deseases', to: 'crops#get_deseases'
  end

  scope module: 'config/production', path: 'treatments' do
    get '/treatment_exist', to: 'treatments#treatment_exist'
  end

  namespace :config do
    resources :taxes
    resources :drivers
    resources :units
    resources :boxes
    resources :delivery_addresses
    resources :client_brands
    resources :currencies
    namespace :production do
      root to: 'main#index'
      resources :categories
      resources :treatments
      resources :active_ingredients
      resources :presentations
      resources :supplies do
        member do
          delete '/delete_image', to: 'supplies#delete_image_attachment'
        end
        resources :treatments
        resources :presentations, only: %i[update edit show]
        resources :active_ingredients, only: %i[update edit show]
      end
      resources :ranches do
        resources :areas
        resources :perforations
      end
      resources :production_units, except: %i[show]
      resources :weight_units, only: %i[index create destroy]
      resources :irrigation_types, only: %i[index create destroy]
      resources :areas
      resources :activities
      resources :perforations
      resources :stages
      resources :sub_stages
      resources :crops do
        resources :deseases
        resources :pests
        member do
          get '/get_colors', to: 'crops#get_colors'
          get '/get_qualities', to: 'crops#get_qualities'
          get '/get_sizes', to: 'crops#get_sizes'
          get '/get_packages', to: 'crops#get_packages'
        end
      end
      resources :products
      resources :sizes
      resources :qualities
      resources :colors
      resources :packages
      resources :hosts
      resources :damages
      resources :pests do
        resources :treatments
        resources :hosts
        resources :damages
        member do
          patch '/update_pictures', to: 'pests#update_pictures'
        end
      end
      resources :deseases do
        resources :treatments
        resources :hosts
        resources :damages
        member do
          patch '/update_pictures', to: 'deseases#update_pictures'
        end
      end
    end
    namespace :admin do
      resources :expense_concepts
    end
    resources :clients, except: [:edit]
  end

  namespace :logistic do
    root to: 'main#index'
    resources :freights
    resources :carriers do
      resources :drivers
      resources :units
      resources :freights
      resources :boxes
      resources :contacts, except: [:index]
      resources :bank_accounts, except: [:index]
    end
    resources :bank_accounts, except: [:index]
    resources :contacts, except: [:index]
    resources :units
    resources :drivers
    resources :boxes
    namespace :config do
      root to: 'main#index'
      resources :box_types
      resources :unit_brands
    end
  end

  namespace :commercial do
    root to: 'main#index' # Comercial dashboard
    resources :requisitions do
      get '/print', to: 'requisitions#print'
      patch '/update_status', to: 'requisitions#update_status'
    end
    resources :providers do
      patch :update_status
      resources :addresses
      get :supplies
      patch :add_supplies
      patch :delete_supply
    end
    namespace :config do
      root to: 'main#index'
      resources :delivery_types, except: [:show, :new]
      resources :provider_categories do
        get '/get_subcategories', to: 'provider_categories#get_subcategories'
      end
    end
  end

  namespace :credit do
    resources :payment_advances
  end

  namespace :billing do
    resources :pre_bills do
      patch :update_discounts
      patch :manual_stamp
      patch :cancel
    end
  end

  namespace :crm do
    root to: 'main#index' # CRM dashboard
    resources :report_prices, except: %i[index show]
    resources :products, only: %i[edit update]
    resources :expenses, except: %i[index show] do
      collection do
        get 'build_detail'
      end
    end
    resources :clients do
      collection do
        get 'delivery_addresses'
      end
      resources :contacts, except: [:index]
      resources :delivery_addresses, except: [:index]
      resources :contracts, only: %i[new edit show]
      resources :bank_accounts, except: [:index]
      resources :fiscals, except: [:index]

      get '/get_delivery_address', to: 'clients#get_delivery_address'
      get '/get_contacts', to: 'clients#get_contacts'
    end
    resources :sales do
      patch '/expenses', to: 'sales#update_expenses'
      patch '/products', to: 'sales#update_products'
      patch '/reports', to: 'sales#update_reports'
      patch '/cancel', to: 'sales#cancel'
      patch '/set_contract', to: 'sales#set_contract'
      patch '/update_currency', to: 'sales#update_currency'
      patch '/documents', to: 'sales#update_documents'
      get '/to_collect', to: 'sales#to_collect'
      get '/manage', to: 'sales#manage'
      get '/get_report_products', to: 'sales#get_report_products'
    end
    resources :contracts, only: %i[create update]
    resources :bank_accounts, except: [:index]

    resources :delivery_addresses, except: [:index] do
      collection do
        patch :update_prices
      end
    end
    resources :contacts, except: [:index]
    resources :fiscals, except: [:index]
    resources :quotes do
      get '/print', to: 'quotes#print'
      patch '/update_status', to: 'quotes#update_status'
      patch '/cancel', to: 'quotes#cancel'
      collection do
        get :consolidate
      end
    end
    resources :sales_orders do
      get '/print', to: 'sales_orders#print'
      patch '/cancel', to: 'sales_orders#cancel'
      get '/print_aditional_data', to: 'sales_orders#print_aditional_data'
    end

    namespace :config do
      root to: 'main#index'
      resources :expenses
    end
  end

  namespace :directories do
    resources :carriers do
      resources :drivers
    end
    resources :clients
  end

  namespace :addresses do
    resources :countries
    resources :states
    resources :municipalities
    # #End points to addres
    get '/addresses/states', to: 'addresses#states'
    get '/addresses/municipalities', to: 'addresses#municipalities'
    get '/addresses/locations', to: 'addresses#locations'
  end

  namespace :traceability do
    resources :cicles do
      patch '/update_status', to: 'cicles#update_status'
    end
    resources :areas, only: [:index, :show]
    resources :harvests do
      collection do
        get '/get_crop', to: 'harvests#get_crop'
      end
    end
  end

  resources :carriers do
    get '/get_drivers', to: 'carriers#get_drivers'
    get '/get_units', to: 'carriers#get_units'
    get '/get_boxes', to: 'carriers#get_boxes'
  end

  resources :shipments do
    get '/consolidate', to: 'shipments#consolidate'
    get '/print', to: 'shipments#print'
    get '/print_responsive', to: 'shipments#print_responsive'
  end

  resources :companies
  resources :profile, except: [:new] do
    get '/avatar', to: 'profile#avatar'
    get '/change_password', to: 'profile#change_password'
  end

  devise_for :users
  root to: 'dashboard#index'
end

app/controllers/commercial/config/delivery_types_controller.rb
module Commercial
  module Config
    class DeliveryTypesController < ApplicationController
      before_action :set_object, only: %i[edit update destroy]

      add_breadcrumb "Commercial", :commercial_root_path
      add_breadcrumb "Configuración", :commercial_config_root_path

      def index
        add_breadcrumb "Tipos de entrega"

        @delivery_types = DeliveryType.all
        @delivery_type = DeliveryType.new
        
        search if params[:q].present?
        @delivery_types = @delivery_types.paginate(page: params[:page], per_page: 25)
      end

      def create
        @delivery_type = DeliveryType.new(delivery_type_params)
        @delivery_type.save
        msg = "<i class='fas fa-check-circle mr-2'></i> Tipo de entrega creada correctamente"
        flash[:notice] = msg
        redirect_to commercial_config_delivery_types_path
      end

      def update
        @delivery_type.update(delivery_type_params)
        msg = "<i class='fas fa-check-circle mr-2'></i> Tipo de actualizada correctamente"
        flash[:notice] = msg
        redirect_to commercial_config_delivery_types_path
      end

      private

      def delivery_type_params
        params.require(:delivery_type).permit(:id, :name)
      end

      def set_object
        @delivery_type = DeliveryType.find(params[:id])
      end

      def search
        query = Regexp.escape(params[:q])

        @delivery_types = @delivery_types.where("name ~* ?", query)
      end
    end
  end
end

app/controllers/commercial/config/main_controller.rb
# frozen_string_literal: true

module Commercial
  module Config
    class MainController < ApplicationController
      def index
        add_breadcrumb 'Commercial', :commercial_root_path
        add_breadcrumb 'Configuración', :commercial_config_root_path
      end
    end
  end
end

app/controllers/commercial/config/provider_categories_controller.rb
# frozen_string_literal: true

module Commercial
  module Config
    class ProviderCategoriesController < ApplicationController
      before_action :set_object, only: %i[edit update destroy get_subcategories]

      add_breadcrumb 'Comercial', :commercial_root_path
      add_breadcrumb 'Proveedores', :commercial_providers_path
      add_breadcrumb 'Configuración', :commercial_config_root_path
      add_breadcrumb 'Categorías de proveedores', :commercial_config_provider_categories_path

      def index
        @categories = ProviderCategory.paginate(page: params[:page], per_page: 16)

        search if params[:q].present?
      end

      def new
        add_breadcrumb 'Nuevo Categoría'
        @category = ProviderCategory.new
        @category.subcategories.build
      end

      def edit
        add_breadcrumb 'Editar'
      end

      def create
        @category = ProviderCategory.new(provider_category_params)

        if @category.save
          msg = "<i class='fas fa-check-circle mr-2'></i> Categoría creada correctamente "
          flash[:notice] = msg
          redirect_to commercial_config_provider_categories_path
        else
          add_breadcrumb 'Nuevo Categoría'
          render :new
        end
      end

      def update
        if @category.update(provider_category_params)
          msg = "<i class='fas fa-check-circle mr-2'></i> Categoría actualizada correctamente"
          flash[:notice] = msg
          redirect_to commercial_config_provider_categories_path
        else
          render :edit
        end
     end

      def destroy
        @category.destroy
      end

      def get_subcategories
        render json: @category.subcategories
      end

      private

      def search
        q = Regexp.escape(params[:q])

        @categories = @categories.where('name ~* ?', q)
      end

      def provider_category_params
        params.require(:provider_category).permit(:name,
                                                  subcategories_attributes: %i[id name description categorytable_type categorytable_id _destroy])
      end

      def set_object
        id = params[:id].present? ? params[:id] : params[:provider_category_id]
        @category = ProviderCategory.find(id)
      end
    end
  end
end

app/controllers/concerns/breadcrumbs/logistic/config/box_types.rb
# frozen_string_literal: true

module Breadcrumbs::Logistic::Config
  module BoxTypes
    extend ActiveSupport::Concern

    included do
      add_breadcrumb 'Logistica', :logistic_root_path
      add_breadcrumb 'Configuración', :logistic_config_root_path
      add_breadcrumb 'Tipos de Cajas', :logistic_config_box_types_path
    end

    def build_breadcrumbs
      add_breadcrumb t("breadcrumbs.#{action_name}")
    end
  end
end

app/controllers/config/admin/expense_concepts_controller.rb
module Config
  module Admin
    class ExpenseConceptsController < ApplicationController
      before_action :set_object, only: %i[destroy]
    
      add_breadcrumb "Config", :config_production_root_path
      add_breadcrumb "Admin"
      add_breadcrumb "Coneptos de gastos", :config_admin_expense_concepts_path
      
      def index
        @concepts = ExpenseConcept.paginate(page: params[:page], per_page: 25)
        @concept = ExpenseConcept.new()

        filter_by_query if params[:query].present?
      end

      def create
        @concept = ExpenseConcept.new(conept_params)
        if @concept.save
          flash[:notice] = "<i class='fa fa-check-circle mr-1 s-18'></i>  Concepto creado correctamente"
          redirect_to config_admin_expense_concepts_path
        else
          @concept = ExpenseConcept.new(conept_params)
          render :index
        end
      end

      def destroy
        @concept.destroy
      end

      private

      def filter_by_query
        query = Regexp.escape(params[:query])
        
        @concepts = @concepts.where("name ~* ?", query)
      end

      def conept_params
        params.require(:expense_concept).permit(:name)
      end

      def set_object
        @concept = ExpenseConcept.find(params[:id])
      end
    end
  end
end

app/controllers/config/client_brands_controller.rb
# frozen_string_literal: true

module Config
  class ClientBrandsController < ApplicationController
    before_action :set_object, only: %i[edit update destroy]
    add_breadcrumb 'Marcas', :config_client_brands_path

    def index
      @brands = ClientBrand.paginate(page: params[:page], per_page: 16)
      search if params[:q].present?
      search_by_client if params[:c].present?
    end

    def edit
      add_breadcrumb 'Editar'
    end

    def show
      add_breadcrumb 'Detalle'
    end

    def new
      add_breadcrumb 'Nueva'
      @brand = ClientBrand.new
    end

    def create
      @brand = ClientBrand.new(brand_params)
      if @brand.save
        flash[:notice] = 'Marca creada'
        return redirect_to client_path(params[:c]) if params[:c].present?

        redirect_to config_client_brands_path
      else
        render :new, client_id: params[:c]
      end
    end

    def update
      if @brand.update(brand_params)
        flash[:notice] = 'Marca actualizada'
        redirect_to config_client_brands_path
      else
        render :edit
      end
    end

    def destroy
      @brand.destroy
    end

    private

    def search
      q = Regexp.escape(params[:q])
      @brands = @brands.where('name ~* ?', q)
    end

    def search_by_client
      client_id = Regexp.escape(params[:c])
      @brands = @brands.where(client_id: client_id)
    end

    def brand_params
      params.require(:client_brand).permit(:name, :client_id)
    end

    def set_object
      @brand = ClientBrand.find(params[:id])
    end
  end
end

app/controllers/config/clients_controller.rb
# frozen_string_literal: true

module Config
  class ClientsController < ApplicationController
    add_breadcrumb 'Configuración'

    def index
      add_breadcrumb 'Clientes'
      @clients = Client.all

      filter_by_query if params[:query].present?
    end

    def show
      @client = Client.find(params[:id])
      @client_config = @client.settings.present? ? @client.settings : ClientConfig.new(client_id: @client.id)
    end

    def create
      @client_config = ClientConfig.new(client_config_params)
      if @client_config.save
        flash[:notice] = "<i class='fa fa-check-circle mr-1 s-16'></i>  Configuración guardada correctamente"
        redirect_to config_client_url(@client_config.client_id, tab: :sales)
      end
    end

    def update
      @client_config = Client.find(params[:id]).settings
      if @client_config.update(client_config_params)
        flash[:notice] = "<i class='fa fa-check-circle mr-1 s-16'></i>  Configuración guardada correctamente"
        redirect_to config_client_url(@client_config.client_id, tab: :sales)
      end
    end

    def client_config_params
      params.require(:client_config).permit(:id, :currency_id, :pay_freight,
                                            :client_type, :client_id, :credit_days, :date_due)
    end

    private

    def filter_by_query
      query = Regexp.escape(params[:query])
      @clients = @clients.where('name ~* ?', query)
    end
  end
end

app/controllers/config/production/main_controller.rb
# frozen_string_literal: true

module Config::Production
  class MainController < ApplicationController
    add_breadcrumb 'Produccion', :config_production_root_path
    def index; end
  end
end

app/views/config/delivery_addresses/edit.html.slim
section.content-header.pb-0
  .container-fluid
    .row.mb-2
      .col-sm-6
        h5 Editar dirección de entrega 
      .col-sm-6.text-right.pr-2.s-12
        = render_breadcrumbs :separator => ' / '
section.content
  .container-fluid
    = render "shared/form_info"
    .card
      .card-body.p-3
        .row
          .col-lg-7
            = render 'form', states: @states, municipalities: @municipalities

app/views/config/delivery_addresses/index.html.slim
section.content-header.pb-0
	.container-fluid
		.row.mb-2
			.col-sm-6
				h5 Direcciónes de entrega
			.col-sm-6.text-right.pr-2.s-12
				= render_breadcrumbs :separator => ' / '
section.content
  .container-fluid
    .row
      .col-lg-12
        = render "shared/alerts"
      .col-md-12
        .card
          .card-header.p-2.pb-1.bg-light-gray
            .row
              .col-md-8.col-sm-12
                = form_tag(config_delivery_addresses_path, method: "GET") do
                  - value = params[:q].present? ? params[:q] : ''
                  .form-row.align-items-center
                    .col-6
                      label.s-12.mb-0 Busqueda
                      = text_field_tag(:q, value, class: 'form-control form-control-sm', placeholder: 'Busqueda por Nombre, telefono y/o persona de contacto')
                    .col-4
                      label.s-12.mb-0 Cliente
                      = select_tag :c, options_for_select(Client.all.pluck(:name, :id), selected: params[:c]), include_blank: 'Cliente', class: 's-12 slim-select'
                    .col-2.my-1
                      button.btn.btn-sm.btn-flat.btn-default.bold.mt-4 type="submit"  
                        svg.svg-inline--fa.fa-filter.fa-w-16.h-14 aria-hidden="true" data-icon="filter" data-prefix="fas" focusable="false" role="img" viewbox=("0 0 512 512") xmlns="http://www.w3.org/2000/svg" 
                          path d=("M487.976 0H24.028C2.71 0-8.047 25.866 7.058 40.971L192 225.941V432c0 7.831 3.821 15.17 10.237 19.662l80 55.98C298.02 518.69 320 507.493 320 487.98V225.941l184.947-184.97C520.021 25.896 509.338 0 487.976 0z") fill="currentColor"
              .col-md-4.col-sm-6.text-right.pt-1
                = link_to new_config_delivery_address_path, class: 'btn btn-success btn-sm s-12 mt-4' do 
                  svg.svg-inline--fa.fa-plus-circle.fa-w-16.h-14 aria-hidden="true" data-icon="plus-circle" data-prefix="fas" focusable="false" role="img" viewbox=("0 0 512 512") xmlns="http://www.w3.org/2000/svg" 
                    path d=("M256 8C119 8 8 119 8 256s111 248 248 248 248-111 248-248S393 8 256 8zm144 276c0 6.6-5.4 12-12 12h-92v92c0 6.6-5.4 12-12 12h-56c-6.6 0-12-5.4-12-12v-92h-92c-6.6 0-12-5.4-12-12v-56c0-6.6 5.4-12 12-12h92v-92c0-6.6 5.4-12 12-12h56c6.6 0 12 5.4 12 12v92h92c6.6 0 12 5.4 12 12v56z") fill="currentColor" 
                  span.pl-2 Nueva dirección de entrega
             
          .card-body.table-responsive.p-0
            table.table.table-sm.table-hover.text-nowrap.table-bordered.s-14
              thead
                tr.bg-light-gray
                  th style=("width: 5%")  #
                  th Nombre
                  th Telefono
                  th Cliente
                  th Estado
                  th Dirección
                  th Terceros
                  th.text-cener colspan="2" style=("width: 12%") Acciónes
              tbody#tbody
                - if @delivery_addresses.empty?
                  tr
                    td.text-center colspan="6"
                      = link_to 'Nuevo registro', new_config_box_path, class: "s-12" 
                - else
                  - @delivery_addresses.each do |da|
                    tr
                      td = da.id
                      td = da.name.upcase
                      td = da.phone
                      td = da.client.name.upcase
                      td = da.municipality.name.upcase
                      td = da.address.upcase
                      td = da.external.present? ? "SI" : "NO"
                      td.text-center
                        = link_to config_delivery_address_path(da), title: "Ver detalle", 'data-toggle' => 'tooltip', 'data-placement' => 'left', class: 'mr-1' do
                         svg.feather.feather-eye fill="none" height="16" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox=("0 0 24 24") width="24" xmlns="http://www.w3.org/2000/svg" 
                          path d=("M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z") 
                          circle cx="12" cy="12" r="3"
                        = link_to edit_config_delivery_address_path(da), title: "Editar", 'data-toggle' => 'tooltip', 'data-placement' => 'left' do
                          svg.feather.feather-edit.mr-2 fill="none" height="16" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox=("0 0 24 24") width="16" xmlns="http://www.w3.org/2000/svg" 
                            path d=("M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7") 
                            path d=("M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z")
                        = link_to config_delivery_address_path(da), title: "Eliminar", data: { placement: 'left', toggle: 'tooltip', controller: 'users', behavior: 'delete' }  do
                         svg.feather.feather-trash-2.text-danger fill="none" height="16" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox=("0 0 24 24") width="16" xmlns="http://www.w3.org/2000/svg" 
                          polyline points=("3 6 5 6 21 6") 
                          path d=("M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2") 
                          line x1="10" x2="10" y1="11" y2="17" 
                          line x1="14" x2="14" y1="11" y2="17"
          .card-footer.p-2.pb-1.bg-light-gray
            .row
              .col-lg-12.d-flex.justify-content-center
                .digg_pagination.mt-2.s-14
                  = will_paginate @delivery_addresses, :container => false, :page_links => true

app/views/config/delivery_addresses/new.html.slim
section.content-header.pb-0
  .container-fluid
    .row.mb-2
      .col-sm-6
        h5 Nueva dirección de entrega 
      .col-sm-6.text-right.pr-2.s-12
        = render_breadcrumbs :separator => ' / '
section.content
  .container-fluid
    = render "shared/form_info"
    .card
      .card-body.p-3
        .row
          .col-lg-7
            = render 'form', states: [], municipalities: []